services:
  - type: web
    name: npustmis-django-system
    env: python
    buildCommand: cd src && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: bash -c "cd src && export PYTHONPATH=$(pwd) && gunicorn system.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
databases:
  - name: mydb